"use client"
import {useContext } from 'react'
import CartView from '@/Components/Cart/CartView';
import { CartContext } from '@/Context/CartContext';
import AslLoad from '@/Components/Global/AslLoad';

export const metadata = {
    title: 'سبد خرید',
    description: 'Generated by create next app',
}

const Cart = () => {
  const {cart,loading} = useContext(CartContext)

  return (
    <>
    {
      loading ?
      <AslLoad />
      :
      <CartView data={cart} />
    }
    </>
    
  )
}

export default Cart

