"use client"
import {useContext } from 'react'
import CartView from '@/Components/Cart/CartView';
import { CartContext } from '@/Context/CartContext';

export const metadata = {
    title: 'سبد خرید',
    description: 'Generated by create next app',
}

const Cart = () => {
  const {cart} = useContext(CartContext)

  return (
    <CartView data={cart} />
  )
}

export default Cart

