"use client"
import { BASE_URL, DOMAIN } from '@/utils/constans';
import axios from 'axios';
import {useContext,useState , useEffect} from 'react'
import ListItems from '@/components/cart/listItems';
import Link from 'next/link';
import { AuthContext } from '@/Context/AuthContext';
import Loading from '@/Components/Global/Loading';
import { useRouter } from 'next/navigation';

export const metadata = {
    title: 'سبد خرید',
    description: 'Generated by create next app',
}


const Cart = () => {
  const {user} = useContext(AuthContext)
  const [data, setData] = useState(null)

  const getData = async () => {
    await axios.post(`${BASE_URL}/user/cart/getCart`,null,{
        withCredentials:true
      }).then(response => {
          if(response.data.success){
              setData(response.data.data)
          }else{
            alert(response.data.messgae)
          }
      }).catch(err => {
          console.log(err.messgae)
      })
  }

  useEffect(() => {
    getData()
  }, [])


  

  return (
    <>
      {
        <div className='container'>
          <div className='flex-between'>
            <h2 className='ireg'>سبد خرید شما</h2>
            <Link className='btnDef' href={(user) ? '/address' : '/singin' }>مرحله بعدی</Link>
            {/* <button className='btnDef' onClick={nexting} >مرحله بعدی</button> */}
          </div>
          {(data &&  data.length > 0) ? <ListItems data={data} /> : ""}
          {data && data.err && <h2>{data.err}</h2>}
        </div>
      }
    </>
    
  )
}

export default Cart

