import { BASE_URL } from '@/utils/constans';
import axios from 'axios';
import React from 'react'

export const metadata = {
    title: 'مقاله',
    description: 'Generated by create next app',
  }

const Article = async (props) => {
    // const res = await fetch(`${BASE_URL}/user/option/getArticleById`,{
    //     headers :{"Content-Type": "application/json"},
    //     cache:"no-store",
    //     method:"POST",
    //     body:{id:props.params.articleId}
    //   })
    //   const data = await res.json();
      const data = await axios.post(`${BASE_URL}/user/option/getArticleById`,{
        id:props.params.articleId
        },{cache: 'no-store'})

  return (
    <div className='container' dangerouslySetInnerHTML={{ __html: data.data.data.content }}></div>
  )
}

export default Article