"use client"
import { BASE_URL, DOMAIN } from '@/utils/constans'
import axios from 'axios'
import { useRouter } from 'next/navigation'
import React, { useContext , useEffect , useState} from 'react'
import { CartContext } from '@/Context/CartContext'
import FinalList from '@/Components/Final/FinalList'

export const metadata = {
    title: 'مشاهده نهایی',
    description: 'Generated by create next app',
}

const Final = () => {
    const router = useRouter();
    const {cart} = useContext(CartContext)
    const [data, setdata] = useState(null)

    const nextStage = () => {
        if(cart.length > 0){
            router.push('/pay')
        }else{
            alert('جهت ورود به مرحله پرداخت باید محصولی را به سبد خرید خود اضافه کنید')
        }
    }  

    const getData = async () => {
        await axios.post(`${BASE_URL}/user/order/newOrder`,null,{withCredentials:true}).then(response => {
              console.log(response.data)
              if(response.data.success){
                  setdata(response.data.data)
              }else{
                console.log(response.data.messgae)
              }
          }).catch(err => {
              console.log(err.messgae)
          })
    }

    useEffect(() => {
        getData()
    }, [])
    

  return (
    <div className='container'>
        {
            data && 
            <div>
                <div className='flex-between'>
                    <h2 className='ireg'>سبد خرید شما</h2>
                    <button onClick={() => {nextStage()}} className='btnDef'>مرحله بعدی</button>
                </div>
            {data && <FinalList data={data} />}
                
            </div>
        }
    </div>
  )
}

export default Final

