import './globals.css'
import { Inter } from 'next/font/google'
import ProductContext from '@/Context/ProductContext'
import Header from '@/Components/Header/Header'
import Footer from '@/Components/Footer/Footer'
import { AuthWrapper } from '@/Context/AuthContext'
import { CartWrapper } from '@/Context/CartContext'
import axios from 'axios'
import { AddressWrapper } from '@/Context/AddressContext'
import LoadingIndicator from '@/Components/Global/Loadand'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import 'react-circular-progressbar/dist/styles.css';

import 'swiper/swiper-bundle.css';
import Login from '@/Components/Global/Login'
import CartView from '@/Components/Product/CartView'
import { PaymentWrapper } from '@/Context/PaymentContext'

// const inter = Inter({ subsets: ['latin'] })
axios.defaults.withCredentials = true;

export const metadata = {
  title: 'فروشگاه اینترنتی',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,href }) {
  return (
    <html lang="en">
            <body>
            <AuthWrapper>
              <CartWrapper>
                <PaymentWrapper>
                  <ProductContext>
                    <AddressWrapper>
                      <Header />
                      {/* <LoadingIndicator /> */}
                      {children}
                      <Footer />
                      <Login />
                      <CartView />
                    </AddressWrapper>
                  </ProductContext>
                </PaymentWrapper>
              </CartWrapper>
            </AuthWrapper>
            </body>
    </html>
  )
}
