
import MySlider from "@/Components/Home/MySlider/MySlider";
import ListItems from "@/Components/Home/listitems/listItems";
import SliderLeft from "@/Components/Home/sliderTopLeft/Slider";
import { BASE_URL } from "@/utils/constans"
import slider1 from "../public/images/slider1.webp"
import slider2 from "../public/images/slider2.webp"
import slider3 from "../public/images/slider3.webp"
import CategorySlider from "@/Components/Home/categorySlider/CategorySlider";
import {CiBank,CiBaseball,CiBowlNoodles,CiCoffeeCup,CiDeliveryTruck} from "react-icons/ci"
import Slider4 from "@/Components/Home/slider4/Slider4";
import Slider5 from "@/Components/Home/slider5/Slider5";
import Slider6 from "@/Components/Home/slider6/Slider6";
import Takhfif from "@/Components/Home/takhfif/Takhfif";
import Tabligh from "@/Components/Home/tabligh/Tabligh";
import Slider7 from "@/Components/Home/slider7/Slider7";
import Slider8 from "@/Components/Home/slider8/Slider8";

export const metadata = {
  title: 'فروشگاه دلبر شاپ',
  description: 'Generated by create next app',
}

export default async function Home(props) {

  const res = await fetch(`${BASE_URL}/user/option/getHome`,{
    headers :{"Content-Type": "application/json"},
    cache:"no-store",
    method:"GET"
  })
  const data = await res.json();

  const sl5Data = [
    {
      id:1,
      name:"لپ تاپ 17 اينچي ام اس آي مدل GS72 6QE Stealth Pro",
      discount:2000000,
      price:2300000,
      perc:"10%",
      vizh:[
        {name:"نعدادسیم کارت",value:" 2 سیم کارت"},
        {name:"دوربین",value:"48 مگاپیکسل"},
        {name:"حافظه داخلی",value:"64 گیگابایت"},
        {name:"مقدار رم",value:"3 گیگ"},
      ],
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/10/pocox3-550x550.webp"
    },
    {
      id:2,
      name:"لپ تاپ 15 اينچي لنوو مدل Ideapad 320 – H",
      discount:2000000,
      price:2300000,
      perc:"4%",
      vizh:[
        {name:"نعدادسیم کارت",value:" 2 سیم کارت"},
        {name:"دوربین",value:"48 مگاپیکسل"},
        {name:"حافظه داخلی",value:"64 گیگابایت"},
        {name:"مقدار رم",value:"3 گیگ"},
      ],
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2019/03/aplle-550x550.webp"
    },
    {
      id:3,
      name:"گوشی موبایل اپل مدل iPhone 12 A2404 دو سیم‌ کارت ظرفیت 128 گیگابایت",
      discount:2000000,
      price:2300000,
      perc:"20%",
      vizh:[
        {name:"نعدادسیم کارت",value:" 2 سیم کارت"},
        {name:"دوربین",value:"48 مگاپیکسل"},
        {name:"حافظه داخلی",value:"64 گیگابایت"},
        {name:"مقدار رم",value:"3 گیگ"},
      ],
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2017/10/1-5-600x600.jpg"
    }
  ]

  const mostSale = [
    {
      id:1,
      name:"تلويزيون ال اي دي هوشمند سامسونگ مدل 55KU7970 سايز 55 اينچ",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2017/10/1-32-75x75.jpg",
      price:850000,
      discount:0,
      rate:4.5
    },
    {
      id:2,
      name:"کوله پشتی کينگ کمپ مدل Peach 28",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/06/01-75x75.png",
      price:246500,
      discount:0,
      rate:4.0
    },
    {
      id:3,
      name:"گوشی موبایل اپل مدل iPhone 12 A2404 دو سیم‌ کارت ظرفیت 128 گیگابایت",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2019/03/aplle-75x75.webp",
      price:430000,
      discount:0,
      rate:4.5
    },
    {
      id:4,
      name:"تلويزيون ال اي دي هوشمند سامسونگ مدل 55KU7970 سايز 55 اينچ",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2017/10/1-32-75x75.jpg",
      price:850000,
      discount:0,
      rate:4.5
    },
    {
      id:5,
      name:"کوله پشتی کينگ کمپ مدل Peach 28",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/06/01-75x75.png",
      price:246500,
      discount:0,
      rate:4.0
    },
    {
      id:6,
      name:"گوشی موبایل اپل مدل iPhone 12 A2404 دو سیم‌ کارت ظرفیت 128 گیگابایت",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2019/03/aplle-75x75.webp",
      price:430000,
      discount:0,
      rate:4.5
    },
  ]

  const danesh = [
    {
      id:1,
      title:"فوکوس ۹: جنگ جهانی دوم به روایت سازندگان Call of Duty WWII",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/07/maxresdefault-256x170.webp"
    },
    {
      id:2,
      title:"تاثیر هوش مصنوعی بر بازاریابی دیجیتال",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/07/ai-256x170.webp"
    },
    {
      id:3,
      title:"“قدر تو را می‌دانم”، یک شب مادرانه و دلچسب",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/07/mother-256x170.webp"
    },
    {
      id:4,
      title:"پیوند فوتبال و تکنولوژی در جام جهانی 2018 روسیه",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/07/var-256x170.webp"
    },
    {
      id:5,
      title:"تاثیر هوش مصنوعی بر بازاریابی دیجیتال",
      image:"https://demos.mahdisweb.net/digiland/wp-content/uploads/2018/07/ai-256x170.webp"
    },
  ]

  
  return (
    <div className="container">

      {/* Top Sliders */}
      <div className="flex-between">
        <div className="compRight">
           {data && <MySlider data={data.data.SliderTop}  />}
        </div>
        <div className="compLeft">
           {data && <SliderLeft data={data.data.SliderMoment}  />}
        </div>
      </div>

      {/* Category Slider */}
      <div className="catslider">
        {data && <CategorySlider data={data.data.Categorys} />}
      </div>

      <div className="centersec">
         <div className="sec3Right">
            {data && <Slider4 data1={data.data.ProSlider} />}
         </div> 

         <div className="sec3Left">
            {data && <Slider5 slides={sl5Data} data1={data.data.ShegeftSlider} />} 
         </div>
      </div>

      <div className="sec4">
        {data && <Slider6  data={data.data.NewsProduct} />} 
      </div>

      <div className="sec5">
        <Takhfif />
        <Tabligh />
      </div>

      <div className="sec6">
        <Slider7 data={mostSale} />
      </div>

      <div className="sec7">
          {data && <Slider8  data={data.data.SliderArticle} />} 
      </div>

      {/* <ListItems data={data.data} /> */}
    </div>
  )
}
