"use client"
import Loading from '@/components/global/Loading';
import { CartContext } from '@/Context/CartContext';
import { BASE_URL } from '@/utils/constans';
import axios from 'axios';
import Link from 'next/link';
import {useState,useEffect, useContext} from 'react'


export const metadata = {
    title: 'فاکتور نهایی',
    description: 'Generated by create next app',
}

const Pay = () => {
    const [selectedOption, setSelectedOption] = useState('');
    const {cart} = useContext(CartContext)
    const [card, setCard] = useState({
        peygiry:'',
    });
    const [loading, setLoading] = useState(false);
    const [data, setdata] = useState(null)

    const handleOptionChange = (event) => {
      setCard({peygiry:'',})  
      setSelectedOption(event.target.value);
    };
    
    const goPayment = async () => {
        setLoading(true)
        if(cart.length > 0){
            const data = {
                method:selectedOption,
                peygiry:card.peygiry
            }
            await axios.post(`${BASE_URL}/api/peyment/peyCartNextPay`,data).then(response => {
                if(response.data.success){
                    console.log(response.data)
                    window.location.href = response.data.data;      
                }else{
                    alert(response.data.message)
                }
            }).catch(err => {
                alert(err.message)
            })
        }else{
            alert('سبد خرید شما خالی هست')
        }
        
        setLoading(false)
    }

    const getData = async () => {
        setLoading(true)
        await axios.get(`${BASE_URL}/user/payment/getPayments`,null,{withCredentials:true}).then(response => {
              if(response.data.success){
                  setdata(response.data.data)
                  setSelectedOption(response.data.data[0].name)
              }else{
                  console.log(response.data.message)
              }
          }).catch(err => {
              console.log(err.messgae)
          })
        setLoading(false)  
    
    }

    useEffect(() => {
    //   if(cart.length < 1) router.replace('/cart');
    getData()
    }, [])
    
  return (
    <>
        {
            loading ? 
            <Loading />
            :
            <div className='container'>
                {
                    data && data.map((item,index) => 
                    <div key={index}>
                        <div>
                            <input type="radio" name="option" value={item.name} checked={selectedOption === item.name} onChange={handleOptionChange} />
                            <span>{item.title}</span>
                        </div>
                    </div>
                    )
                }

                {
                    (selectedOption === 'cardtocard') && 
                    <div>
                        <p>شماره پیگیری را وارد کنید</p>
                        <input value={card.peygiry} onChange={(e) => {setCard({peygiry:e.target.value})}} />
                    </div>
                }
                <button className='mt30' onClick={() => {goPayment()}}>پرداخت</button>
                <br/>
                <Link className='mt30 btnDef' href="pay/result?trans_id=59ee4d65-2a99-48f5-9ab7-d46b26e4b30b&order_id=1683451193918&amount=1000&np_status=OK" >موفق</Link>
                <br/>
                <Link className='mt30 btnDef' href="pay/result?trans_id=01b39c11-bcba-43eb-af95-0651a07f7051&order_id=1683448539709&amount=1000&np_status=Unsuccessful" >ناموفق</Link>

            </div>
        }
    </>
    
  )
}

export default Pay;
